# Site settings
title: ""
email: chiyang10000@gmail.com
description: ""
baseurl: ""
url: "https://chiyang10000.github.io/"
title_description: "我是一只羊"
title_image: #"https://avatars2.githubusercontent.com/u/18636717?s=400&u=e4b9b6e7b694e8e673054c59dc3bc76944d0382b&v=4"
google_analytics: UA-144736730-1
disqus_account: chiyang10000
github_repository: https://github.com/chiyang10000/chiyang10000.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: chiyang10000
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "我是一只羊" 
footer_right: "See the original theme on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: {disable: true}
    # block: {disable: true}
    default_lang: bash

permalink: pretty
exclude: [vendor]
